#!/bin/bash
export EMSCRIPTEN_VERSION=1.39.7

cd ~
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
echo Installing emscripten $EMSCRIPTEN_VERSION
./emsdk install $EMSCRIPTEN_VERSION
./emsdk activate $EMSCRIPTEN_VERSION

source ~/emsdk/emsdk_env.sh
